### PR TITLE
feat: project restructure

### PR DESCRIPTION
**Pull request by xhayper**

### CODE REVIEW

**Comment by iArxic** [comment]
Hey @xhayper 
Could you please explain what are the advantages of this version?

I've seen that the code is more organized
DRPC started replaced with StudioPresence started

What is the 'make it run on push' comment?

**Comment by xhayper** [comment]
this is related to the ci, what i mean by "make it run on push" is make the ci package the software every time a commit is push to any branch.

**Comment by xhayper** [comment]
the only software advantage on this version is 

that the deprecated function is replaced in the client code ( spawn and wait )

and in the server code there's an additional error check on the JSON.parse line, and on client.clearActivity lines.

**Comment by xhayper** [comment]
try catch doesn't work on promise.

**Comment by iArxic** [comment]
looks good, by the way do you know if there is a solution to making the program not be flagged as a virus?

**Comment by xhayper** [comment]
It have to be signed, which is like 200$ for a license

**Comment by iArxic** [comment]
thank you for the information, dont think i will be signing it anytime soon haha

i will be pushing v4 later today

**Comment by xhayper** [comment]
Push it as 3.0.1, follow semver!

**Comment by iArxic** [comment]
hey sorry for my delays on merging this, i've had projects and i didnt have any time (literally developed till 2am) its fun!!
happy new year tho :)

**Comment by xhayper** [comment]
All good!

**Pull request merged**
